### ISSUE TITLE
Unable to send kaomoji in latest commit.

### ISSUE THREAD

**Issue by Avellea** [ohlookitsderpy/kaomoji#11]
The latest commit (and supposedly others, I have not tested) do not pull up the autocomplete window, nor do manually typing emotions work. The plugin returns `There aren't any kaomoji for that emotion! Pick an emotion from the list. If you need help, check out https://github.com/davidcralph/kaomoji!` after every attempt.

**Comment by davidcralph** [comment]
This doesn't work with the previous commits as well, so I think something must have broken on Discord/Powercord's end. I'll keep checking to see when a fix is found.

**Comment by Avellea** [comment]
Sounds good. Let me know if there's any logs I can attempt to provide, though I didn't see anything out of the ordinary on my end when taking a quick look.

**Comment by davidcralph** [comment]
Hi, is this still not working for you?

I've just tested on a fresh install of the latest commit, and it appears to be working fine for me.

**Comment by Avellea** [comment]
Looks to be working again! Thanks for keeping me updated on that, I had kind of forgotten about this issue entirely.

**Comment by davidcralph** [comment]
Great to hear, and no problem! I'll be closing this issue now seeing as it's fixed. Thank you!
