### ISSUE TITLE
Add the "Don't Care Emoji" ?

### ISSUE THREAD

**Issue by GhostOps77** [ohlookitsderpy/kaomoji#12]
this one - `¯\_(ツ)_/¯`

**Comment by davidcralph** [comment]
Thanks for the suggestion but this kaomoji is already built-in on Discord (``/shrug``). Would you prefer there to be a mix of shrugging emotes or something?

**Comment by GhostOps77** [comment]
Oh, sry
forgot about the `/shrug` command as you said
